// Print Template
export default {
  generatedBy: 'Generated by {name} · {date}',
  pdfExportSuccess: 'PDF exported successfully',
  pdfExportFailed: 'PDF export failed',
  printOrder: 'Print Order',
  exportPdf: 'Export PDF',
  exporting: 'Exporting...',
};
