import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { runOpa } from './opa-utils.mjs';

export function ensureDir({ fsModule = fs, dir }) {
  fsModule.mkdirSync(dir, { recursive: true });
}

export function cleanDist({ fsModule = fs, distDir, pathModule = path }) {
  if (!fsModule.existsSync(distDir)) return;
  for (const entry of fsModule.readdirSync(distDir)) {
    fsModule.rmSync(pathModule.join(distDir, entry), { recursive: true, force: true });
  }
}

export function extractBundle({
  bundlePath,
  distDir,
  spawnSyncImpl = spawnSync,
}) {
  const tarRes = spawnSyncImpl('tar', ['-xzf', bundlePath, '-C', distDir], {
    stdio: 'inherit',
    shell: false,
  });
  if (tarRes.error) throw tarRes.error;
  if (tarRes.status !== 0) {
    throw new Error(`failed to extract OPA bundle: ${bundlePath}`);
  }
}

export function writeGeneratedArtifact({
  fsModule = fs,
  pathModule = path,
  policyDir,
  distDir,
  generatedDir,
  generatedArtifact,
  generatedWasmArtifact,
}) {
  const wasmPath = pathModule.join(distDir, 'policy.wasm');
  const dataPath = pathModule.join(distDir, 'data.json');
  const metadataPath = pathModule.join(policyDir, 'metadata.json');

  if (!fsModule.existsSync(wasmPath)) throw new Error(`missing ${wasmPath}`);
  if (!fsModule.existsSync(dataPath)) throw new Error(`missing ${dataPath}`);
  if (!fsModule.existsSync(metadataPath)) throw new Error(`missing ${metadataPath}`);

  const regoData = JSON.parse(fsModule.readFileSync(dataPath, 'utf8'));
  const metadata = JSON.parse(fsModule.readFileSync(metadataPath, 'utf8'));

  ensureDir({ fsModule, dir: generatedDir });
  fsModule.copyFileSync(wasmPath, generatedWasmArtifact);

  const content = `// Auto-generated by scripts/policy/compile-opa.mjs
// Do not edit manually.
export const POLICY_DATA = ${JSON.stringify(regoData, null, 2)};
export const POLICY_METADATA = ${JSON.stringify(metadata, null, 2)};
`;
  fsModule.writeFileSync(generatedArtifact, content, 'utf8');
}

export function createCompileOpaRunner(options = {}) {
  const processObj = options.processObj || process;
  const fsModule = options.fsModule || fs;
  const pathModule = options.pathModule || path;
  const spawnSyncImpl = options.spawnSyncImpl || spawnSync;
  const runOpaImpl = options.runOpaImpl || runOpa;
  const consoleImpl = options.consoleImpl || console;
  const root = options.root || processObj.cwd();
  const policyDir = options.policyDir || pathModule.join(root, 'policy');
  const distDir = options.distDir || pathModule.join(policyDir, 'dist');
  const bundlePath = options.bundlePath || pathModule.join(distDir, 'authz-bundle.tar.gz');
  const generatedDir = options.generatedDir || pathModule.join(root, 'functions', 'lib', 'authz', 'generated');
  const generatedArtifact = options.generatedArtifact || pathModule.join(generatedDir, 'policy-artifact.js');
  const generatedWasmArtifact = options.generatedWasmArtifact || pathModule.join(generatedDir, 'policy-artifact.wasm');

  function main() {
    ensureDir({ fsModule, dir: distDir });
    cleanDist({ fsModule, distDir, pathModule });

    runOpaImpl(['build', '-t', 'wasm', '-e', 'kk/authz/decision', 'policy/authz.rego', '-o', bundlePath]);
    extractBundle({ bundlePath, distDir, spawnSyncImpl });
    writeGeneratedArtifact({
      fsModule,
      pathModule,
      policyDir,
      distDir,
      generatedDir,
      generatedArtifact,
      generatedWasmArtifact,
    });

    consoleImpl.log(`[authz] compiled OPA bundle to ${bundlePath}`);
    consoleImpl.log(`[authz] generated runtime artifact ${generatedArtifact}`);
    consoleImpl.log(`[authz] generated wasm artifact ${generatedWasmArtifact}`);

    return {
      bundlePath,
      generatedArtifact,
      generatedWasmArtifact,
    };
  }

  return {
    main,
    paths: {
      root,
      policyDir,
      distDir,
      bundlePath,
      generatedDir,
      generatedArtifact,
      generatedWasmArtifact,
    },
  };
}

export function runCompileOpaCli(options = {}) {
  return createCompileOpaRunner(options).main();
}
