#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { runOpa } from './opa-utils.mjs';

const root = process.cwd();
const policyDir = path.join(root, 'policy');
const distDir = path.join(policyDir, 'dist');
const bundlePath = path.join(distDir, 'authz-bundle.tar.gz');
const generatedDir = path.join(root, 'functions', 'lib', 'authz', 'generated');
const generatedArtifact = path.join(generatedDir, 'policy-artifact.js');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function cleanDist() {
  if (!fs.existsSync(distDir)) return;
  for (const entry of fs.readdirSync(distDir)) {
    fs.rmSync(path.join(distDir, entry), { recursive: true, force: true });
  }
}

function extractBundle() {
  const tarRes = spawnSync('tar', ['-xzf', bundlePath, '-C', distDir], {
    stdio: 'inherit',
    shell: false,
  });
  if (tarRes.error) throw tarRes.error;
  if (tarRes.status !== 0) {
    throw new Error(`failed to extract OPA bundle: ${bundlePath}`);
  }
}

function writeGeneratedArtifact() {
  const wasmPath = path.join(distDir, 'policy.wasm');
  const dataPath = path.join(distDir, 'data.json');
  const metadataPath = path.join(policyDir, 'metadata.json');

  if (!fs.existsSync(wasmPath)) throw new Error(`missing ${wasmPath}`);
  if (!fs.existsSync(dataPath)) throw new Error(`missing ${dataPath}`);
  if (!fs.existsSync(metadataPath)) throw new Error(`missing ${metadataPath}`);

  const wasmBase64 = fs.readFileSync(wasmPath).toString('base64');
  const regoData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
  const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));

  ensureDir(generatedDir);
  const content = `// Auto-generated by scripts/policy/compile-opa.mjs
// Do not edit manually.
export const POLICY_WASM_BASE64 = '${wasmBase64}';
export const POLICY_DATA = ${JSON.stringify(regoData, null, 2)};
export const POLICY_METADATA = ${JSON.stringify(metadata, null, 2)};
`;
  fs.writeFileSync(generatedArtifact, content, 'utf8');
}

function main() {
  ensureDir(distDir);
  cleanDist();

  runOpa(['build', '-t', 'wasm', '-e', 'kk/authz/decision', 'policy/authz.rego', '-o', bundlePath]);
  extractBundle();
  writeGeneratedArtifact();

  console.log(`[authz] compiled OPA bundle to ${bundlePath}`);
  console.log(`[authz] generated runtime artifact ${generatedArtifact}`);
}

main();

