export const orderActionAdapter = {
  entityType: 'order',
  actionType: 'create_order',
  targetModule: 'orders',
  requiredPermission: 'orders:manage',
  requiredSlots: ['productName', 'salespersonId'],
  optionalSlots: [
    'productId',
    'variantId',
    'quantity',
    'brand',
    'series',
    'sku',
    'size',
    'color',
    'material',
    'remark',
    'deadline',
    'status',
    'fileIds',
  ],
  fieldLabels: {
    productName: '商品名称',
    salespersonId: '销售员',
    productId: '商品ID',
    variantId: '变体ID',
    quantity: '数量',
    brand: '品牌',
    series: '系列',
    sku: 'SKU',
    size: '尺码',
    color: '颜色',
    material: '材质',
    remark: '备注',
    deadline: '交期',
    status: '状态',
    fileIds: '附件',
  },
};
